# Generated by Django 2.0 on 2019-03-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=36, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=35, verbose_name='密码')),
                ('email', models.CharField(max_length=64, unique=True, verbose_name='邮箱')),
                ('icon', models.ImageField(upload_to='icons/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'User_table',
            },
        ),
    ]
