# Generated by Django 2.0 on 2019-03-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='username',
            field=models.CharField(max_length=35, unique=True, verbose_name='用户名'),
        ),
    ]
