# Generated by Django 2.0 on 2019-03-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190329_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='username',
            field=models.CharField(max_length=34, unique=True, verbose_name='用户名'),
        ),
    ]
