# Generated by Django 2.0 on 2019-03-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190329_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterModelOptions(
            name='user_table',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.AlterField(
            model_name='user_table',
            name='username',
            field=models.CharField(max_length=36, unique=True, verbose_name='用户名'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
